### ISSUE TITLE
External ID

### ISSUE THREAD

**Issue by GHXST01** [EddyVerbruggen/nativescript-snapkit#1]
Hey,

Great effort, I have a quick question and I was hoping you could answer it.
Is the External ID provided by Snapchat after login persistent, or is it unique from session to session?

Can we use it to match data to a specific user this way, or is this not intended?

Maybe better stated:
- The "External ID" can be seen as an account-tied identifier (without having to know their usernames).
This way we could actually use the login-kit as form of authentication and know when a user has returned / have a user store data and present it at a later date.

or

- The "External ID" is only unique and persistent for that session (while the user is using the app for example).
This way we can distinguish users in realtime without identifying them or tracking them across sessions, however, since the user is "incognito" we cannot use it for authentication / know when someone has returned etc.

**Comment by EddyVerbruggen** [comment]
Please ask this q to Snap. It’s their SDK giving the id. I have no idea.
